import { Auction, Bid, Notification } from './types';

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: '1',
    title: 'iPhone 14 Pro - 256GB Space Black',
    description: 'Mint condition iPhone 14 Pro. No scratches, includes original box and accessories. Battery health 98%.',
    image: 'https://picsum.photos/seed/iphone/800/600',
    seller: {
      name: 'Priyanshu Paul',
      avatar: 'https://picsum.photos/seed/priyanshu/100/100',
      isVerified: true,
      rating: 4.8,
      memberSince: 'Jan 2023',
      reviewCount: 124,
    },
    currentBid: 72500,
    bidCount: 34,
    uniqueBidders: 12,
    participantCount: 15,
    endTime: new Date(Date.now() + 1000 * 60 * 45).toISOString(), // 45 mins from now
    status: 'ENDING_SOON',
    category: 'Electronics',
    condition: 'Like New',
    startingPrice: 50000,
  },
  {
    id: '2',
    title: 'Vintage Rolex Submariner 1980',
    description: 'Rare vintage Rolex Submariner in excellent working condition. Original dial and bezel. Recently serviced.',
    image: 'https://picsum.photos/seed/rolex/800/600',
    seller: {
      name: 'Vikram Singh',
      avatar: 'https://picsum.photos/seed/vikram/100/100',
      isVerified: true,
      rating: 4.9,
      memberSince: 'Mar 2022',
      reviewCount: 89,
    },
    currentBid: 450000,
    bidCount: 18,
    uniqueBidders: 5,
    participantCount: 8,
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days from now
    status: 'LIVE',
    category: 'Fashion',
    condition: 'Good',
    startingPrice: 300000,
  },
  {
    id: '3',
    title: 'Handmade Kashmiri Silk Saree',
    description: 'Exquisite hand-woven silk saree from Kashmir. Intricate patterns and vibrant colors. Perfect for weddings.',
    image: 'https://picsum.photos/seed/saree/800/600',
    seller: {
      name: 'Anjali Sharma',
      avatar: 'https://picsum.photos/seed/anjali/100/100',
      isVerified: false,
      rating: 4.5,
      memberSince: 'Oct 2023',
      reviewCount: 42,
    },
    currentBid: 12500,
    bidCount: 8,
    uniqueBidders: 4,
    participantCount: 6,
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(), // 5 hours from now
    status: 'LIVE',
    category: 'Fashion',
    condition: 'New',
    startingPrice: 8000,
  },
  {
    id: '4',
    title: 'Sony Alpha a7 IV Mirrorless Camera',
    description: 'Brand new Sony a7 IV. Body only. Includes 2 extra batteries and a 128GB SD card.',
    image: 'https://picsum.photos/seed/camera/800/600',
    seller: {
      name: 'Rahul Verma',
      avatar: 'https://picsum.photos/seed/rahul/100/100',
      isVerified: true,
      rating: 4.7,
      memberSince: 'Jun 2023',
      reviewCount: 215,
    },
    currentBid: 185000,
    bidCount: 22,
    uniqueBidders: 9,
    participantCount: 12,
    endTime: new Date(Date.now() + 1000 * 60 * 10).toISOString(), // 10 mins from now
    status: 'ENDING_SOON',
    category: 'Electronics',
    condition: 'New',
    startingPrice: 150000,
  },
  {
    id: '5',
    title: 'Abstract Oil Painting - "Rising Sun"',
    description: 'Original abstract oil painting on canvas. Signed by the artist. 24x36 inches.',
    image: 'https://picsum.photos/seed/painting/800/600',
    seller: {
      name: 'Sanya Malhotra',
      avatar: 'https://picsum.photos/seed/sanya/100/100',
      isVerified: true,
      rating: 5.0,
      memberSince: 'Feb 2024',
      reviewCount: 12,
    },
    currentBid: 25000,
    bidCount: 12,
    uniqueBidders: 6,
    participantCount: 9,
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(), // 48 hours from now
    status: 'LIVE',
    category: 'Art & Collectibles',
    condition: 'New',
    startingPrice: 15000,
  },
  {
    id: '6',
    title: 'MacBook Air M2 - 16GB RAM, 512GB SSD',
    description: 'Barely used MacBook Air M2. Midnight color. Includes AppleCare+ until 2025.',
    image: 'https://picsum.photos/seed/macbook/800/600',
    seller: {
      name: 'Amit Patel',
      avatar: 'https://picsum.photos/seed/amit/100/100',
      isVerified: true,
      rating: 4.6,
      memberSince: 'Aug 2022',
      reviewCount: 310,
    },
    currentBid: 95000,
    bidCount: 45,
    uniqueBidders: 15,
    participantCount: 22,
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 1).toISOString(), // 1 hour from now
    status: 'ENDING_SOON',
    category: 'Electronics',
    condition: 'Like New',
    startingPrice: 80000,
  }
];

export const MOCK_BIDS: Bid[] = [
  { id: 'b1', bidderName: 'User***23', amount: 72500, time: '2 mins ago', timestamp: '2 mins ago' },
  { id: 'b2', bidderName: 'User***89', amount: 71000, time: '5 mins ago', timestamp: '5 mins ago' },
  { id: 'b3', bidderName: 'User***45', amount: 70000, time: '12 mins ago', timestamp: '12 mins ago' },
  { id: 'b4', bidderName: 'User***23', amount: 68500, time: '15 mins ago', timestamp: '15 mins ago' },
  { id: 'b5', bidderName: 'User***12', amount: 67000, time: '20 mins ago', timestamp: '20 mins ago' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'outbid',
    title: 'Someone outbid you!',
    description: 'Someone outbid you on iPhone 14 Pro — ₹72,500 is now the highest bid',
    timestamp: '10 mins ago',
    isRead: false,
  },
  {
    id: 'n2',
    type: 'won',
    title: '🎉 You won the auction!',
    description: 'You won the auction for Handmade Saree! Complete payment within 24hrs',
    timestamp: '2 hours ago',
    isRead: true,
  },
  {
    id: 'n3',
    type: 'bid',
    title: 'New bid received',
    description: 'Your listing MacBook Air received its first bid of ₹85,000',
    timestamp: 'Yesterday',
    isRead: true,
  },
  {
    id: 'n4',
    type: 'system',
    title: 'Auction ending soon',
    description: '⏰ Auction ending in 10 minutes: Sony Camera',
    timestamp: 'Today',
    isRead: false,
  }
];
